<?php

// load field hooks
module_load_include('inc', 'ting_infomedia', 'includes/ting_infomedia.field');
module_load_include('inc', 'ting_infomedia', 'includes/ting_infomedia.wrapper');



/**
 * Implements hook_theme
 * Set template for viewing ting_infomedia articles.
 * Set theme-function for displaying a link (field) to ting_infomedia
 *
 * @existing; array of existing themes
 * @type; which type is being process (module,base_theme_engine,theme_engine,base_theme,theme)
 * @theme; name of $type being processed
 * @path; directory path of theme or module
 *
 * return a render array http://randyfay.com/node/79
 */
function ting_infomedia_theme( $existing, $type, $theme, $path ) {
  return array(
    'ting_infomedia_button' => array(
      'variables' => array('ting_infomedia_button' => ''),
      'template' => 'theme/ting-infomedia-button',
    ),
    // page view definitions - view articles
    'ting_infomedia_article' => array(
      'template' => 'theme/ting_infomedia_article_view',
      'render element' => 'element',
    ),
  );
}


/**
 * Implements hook_form_FORM_ID_alter (ting_admin_ting_settings) (ie. Ding2)
 * Adding infomedia url form field to ting configuration form
 */
function ting_infomedia_form_ting_admin_ting_settings_alter(&$form, &$form_state, $form_id) {
  $form['infomedia'] = array(
    '#type' => 'fieldset',
    '#title' => t('Helpdesk settings'),
    '#description' => t('Settings for bibdk helpdesk'),
    '#weight' => -3,
  );

  $form['infomedia']['ting_infomedia_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Infomedia web service URL'),
    '#description' => t('URL to the infomedia webservice (access to infomedia article base) , e.g. http://useraccessinfomedia.addi.dk/1.2/'),
    '#required' => TRUE,
    '#default_value' => variable_get('ting_infomedia_url', ''),
  );
}


/**
 * Implements hook_form_FORM_ID_alter (ting_client_admin_webservices_settings) (ie. Bibliotek.dk)
 * Creates a field for adding a URL for the Helpdesk webservice
 */
function ting_infomedia_form_ting_client_admin_webservices_settings_alter(&$form, &$form_state, $form_id) {
  $form['infomedia'] = array(
    '#type' => 'fieldset',
    '#title' => t('Infomedia settings'),
    '#description' => t('Settings for bibdk Infomedia'),
    '#weight' => -3,
  );

  $form['infomedia']['ting_infomedia_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Infomedia web service URL'),
    '#description' => t('URL to the infomedia webservice (access to infomedia article base) , e.g. http://useraccessinfomedia.addi.dk/1.2/'),
    '#required' => TRUE,
    '#default_value' => variable_get('ting_infomedia_url', ''),
  );
}


/**
 * Inline relation types and their titles.
 */
function ting_infomedia_get_ting_relations() {
  static $types;
  if (!$types) {
    $types = array(
      'dbcaddi:hasOnlineAccess' => t('Article from Infomedia'),
    );
  }
  return $types;
}


/**
 * Implements hook_ting_openformat_getobject_params.
 *
 * Add parameters to getObject request.
 */
function ting_infomedia_ting_openformat_getobject_params() {
  return array(
    'relationData' => 'full',
  );
}


